# STAGE 1: BUILDER
FROM dhi.io/python:3-alpine3.23-dev AS builder

WORKDIR /app

COPY ./requirements.txt /app

RUN python -m venv ./venv

RUN addgroup -S frum && adduser -S frum -G frum

RUN apk add --no-cache \
    mariadb-connector-c \
    mariadb-connector-c-dev \
    gcc \
    musl-dev \
    python3-dev \
    curl

RUN ./venv/bin/pip install -r requirements.txt

# STAGE 2: RUNTIME
FROM dhi.io/python:3-alpine3.23

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /etc/shadow /etc/shadow

COPY --from=builder /usr/lib/libmariadb.so* /usr/lib/
COPY --from=builder /usr/lib/mariadb/ /usr/lib/mariadb/

COPY --from=builder /usr/bin/curl /usr/bin/curl
COPY --from=builder /usr/lib/libcurl.so.4 /usr/lib/
COPY --from=builder /usr/lib/libcares.so.2 /usr/lib/
COPY --from=builder /usr/lib/libzstd.so.1 /usr/lib/
COPY --from=builder /usr/lib/libnghttp2.so.14 /usr/lib/
COPY --from=builder /usr/lib/libidn2.so.0 /usr/lib/
COPY --from=builder /usr/lib/libunistring.so.5 /usr/lib/
COPY --from=builder /usr/lib/libpsl.so.5 /usr/lib/
COPY --from=builder /usr/lib/libssl.so.3 /usr/lib/
COPY --from=builder /usr/lib/libcrypto.so.3 /usr/lib/
COPY --from=builder /usr/lib/libz.so.1 /usr/lib/
COPY --from=builder /usr/lib/libbrotlidec.so.1 /usr/lib/
COPY --from=builder /usr/lib/libbrotlicommon.so.1 /usr/lib/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR /app

COPY --chown=frum:frum --from=builder /app/venv /app/venv

COPY --chown=frum:frum ./src /app

USER frum

EXPOSE 5000

HEALTHCHECK --interval=10s --timeout=3s --start-interval=1s \
  CMD ["curl", "-Ss", "http://localhost:5000/health"]

ENTRYPOINT ["/app/venv/bin/python", "api.py"]
