FROM dhi.io/python:3-alpine3.23-dev

WORKDIR /app

COPY ./requirements.txt /app

RUN apk add \
    mariadb-connector-c-dev \
    gcc \
    musl-dev\
    python3-dev

RUN pip install -r requirements.txt

COPY ./src /app

EXPOSE 5000:5000

ENTRYPOINT ["python", "api.py"]
