FROM dhi.io/nginx:1-alpine3.23-dev AS builder

RUN addgroup -S nginx && adduser -S nginx -G nginx

FROM dhi.io/nginx:1-alpine3.23

COPY --from=builder /etc/passwd /etc/passwd

COPY --from=builder /etc/group /etc/group

COPY --from=builder /etc/shadow /etc/shadow

COPY --chown=frum:frum /src /usr/share/nginx/html
