FROM dhi.io/nginx:1-alpine3.23-dev AS builder

RUN apk add curl

FROM dhi.io/nginx:1-alpine3.23

COPY --from=builder /usr/bin/curl /usr/bin/curl
COPY --from=builder /usr/lib/libcurl.so.4 /usr/lib/
COPY --from=builder /usr/lib/libnghttp3.so.9 /usr/lib/
COPY --from=builder /usr/lib/libcares.so.2 /usr/lib/
COPY --from=builder /usr/lib/libzstd.so.1 /usr/lib/
COPY --from=builder /usr/lib/libnghttp2.so.14 /usr/lib/
COPY --from=builder /usr/lib/libidn2.so.0 /usr/lib/
COPY --from=builder /usr/lib/libunistring.so.5 /usr/lib/
COPY --from=builder /usr/lib/libpsl.so.5 /usr/lib/
COPY --from=builder /usr/lib/libssl.so.3 /usr/lib/
COPY --from=builder /usr/lib/libcrypto.so.3 /usr/lib/
COPY --from=builder /usr/lib/libz.so.1 /usr/lib/
COPY --from=builder /usr/lib/libbrotlidec.so.1 /usr/lib/
COPY --from=builder /usr/lib/libbrotlicommon.so.1 /usr/lib/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --chown=nginx:nginx /src /usr/share/nginx/html

HEALTHCHECK --interval=10s --timeout=3s --start-interval=1s \
  CMD ["curl", "-Ss", "http://localhost:8080/index.html"]
