name: Publish Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-back:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/gdblaster/frum/back
          SHA=${{ github.sha }}

          docker build -t $IMAGE_NAME:dev -t $IMAGE_NAME:$SHA ./back

      - name: Push to GHCR
        run: |
          IMAGE_NAME=ghcr.io/gdblaster/frum/back
          SHA=${{ github.sha }}

          docker push $IMAGE_NAME:dev
          docker push $IMAGE_NAME:$SHA

  build-and-push-front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/gdblaster/frum/front
          SHA=${{ github.sha }}

          docker build -t $IMAGE_NAME:dev -t $IMAGE_NAME:$SHA ./front

      - name: Push to GHCR
        run: |
          IMAGE_NAME=ghcr.io/gdblaster/frum/front
          SHA=${{ github.sha }}

          docker push $IMAGE_NAME:dev
          docker push $IMAGE_NAME:$SHA
