name: Publish Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-back:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gdblaster/frum/back:dev ./back

      - name: Push to GHCR
        run: docker push ghcr.io/gdblaster/frum/back:dev

  build-and-push-front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gdblaster/frum/front:dev ./front

      - name: Push to GHCR
        run: docker push ghcr.io/gdblaster/frum/front:dev
