name: Code Check and deployment

on:
  pull_request:

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Prettier Check
        run: npx prettier . --check

  Python-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install python
        uses: actions/setup-python@v6

        with:
          python-version: "3.14"

      - name: Install linting tools
        run: pip install black ruff

      - name: Formating
        run: black . --check

      - name: Lint
        run: ruff check .

  Bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: install bandit
        run: pip install bandit[sarif]

      - name: Bandit scan
        run: |
          bandit -r ./back \
          --severity-level medium \
          --format sarif
          --output bandit.sarif

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install C dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libmariadb-dev \
          gcc \
          libc6-dev \
          python3-dev

      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: back/requirements.txt

  docker-build-front:
    runs-on: ubuntu-latest
    needs: [Bandit-scan, pip-audit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        run: |
          docker build -t frum-front:${{ github.sha }} ./front
          docker save -o front.tar "frum-front:${{ github.sha }}"

      - name: upload image artifact
        uses: actions/upload-artifact@v6
        with:
          name: "front-image-${{github.sha}}"
          path: front.tar
          retention-days: 1
          overwrite: true

  docker-build-back:
    runs-on: ubuntu-latest
    needs: [Bandit-scan, pip-audit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        run: |
          docker build -t frum-back:${{ github.sha }} ./back
          docker save -o back.tar "frum-back:${{ github.sha }}"

      - name: upload image artifact
        uses: actions/upload-artifact@v6
        with:
          name: "back-image-${{github.sha}}"
          path: back.tar
          retention-days: 1
          overwrite: true

  docker-scan-front:
    needs: docker-build-front
    runs-on: ubuntu-latest
    steps:
      - name: import artifact
        uses: actions/download-artifact@v8
        with:
          name: "front-image-${{github.sha}}"

      - name: import image
        run: docker load -i front.tar

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "frum-front:${{ github.sha }}"
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

  docker-scan-back:
    needs: docker-build-back
    runs-on: ubuntu-latest
    steps:
      - name: import artifact
        uses: actions/download-artifact@v8
        with:
          name: "back-image-${{github.sha}}"

      - name: import image
        run: docker load -i back.tar

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "frum-back:${{ github.sha }}"
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
